---
development:
  APP_URL: http://localhost:9090
  TZ: Asia/Taipei
  # Security
  DB_KEY: <32-bit base64 string>
  MSG_KEY: <32-bit base64 string>
  # Sessions & Cache Control
  REDIS_URL: <on heroku credential> # heroku redis
  SESSION_SECRET: <some secrets>
  # AWS SQS
  AWS_ACCESS_KEY_ID: <on aws credential>
  AWS_SECRET_ACCESS_KEY: <on aws credential>
  AWS_REGION: <on aws sqs credential>
  # Google
  GOOGLE_CLIENT_ID: <on gcp credential>
  GOOGLE_CLIENT_SECRET: <on gcp credential>
  REFRESH_TOKEN: <on gcp google drive api credential>
  SAMPLE_FILE_ID: <on google drive credential>
  VIZ_SAMPLE_FILE_ID: <on google drive credential>
  DB_FILENAME: infrastructure/database/dev.db
  # Scheduler
  SIDEKIQ_USER: <sidekiq username>
  SIDEKIQ_PASSWORD: <sidekiq password>

  # Redis Cloud
  REDISCLOUD_VISUALREPORTS_URL: redis://127.0.0.1:6379/
  REDISCLOUD_SIDEKIQ_QUEUES_URL: redis://127.0.0.1:6379/

test:
  APP_URL: http://localhost:9090
  TZ: Asia/Taipei
  # Security
  DB_KEY: <32-bit base64 string>
  MSG_KEY: <32-bit base64 string>
  # Sessions & Cache Control
  REDIS_URL: <on heroku credential>
  SESSION_SECRET: <some secrets>
  # AWS SQS
  AWS_ACCESS_KEY_ID: <on aws credential>
  AWS_SECRET_ACCESS_KEY: <on aws credential>
  AWS_REGION: <on aws sqs credential>
  # Google
  GOOGLE_ACCOUNT: <the one used to apply GCP credentials> # test only
  GOOGLE_CLIENT_ID: <on gcp credential>
  GOOGLE_CLIENT_SECRET: <on gcp credential>
  REFRESH_TOKEN: <on gcp google drive api credential>
  SAMPLE_FILE_ID: <on google drive credential>
  VIZ_SAMPLE_FILE_ID: <on google drive credential>
  DB_FILENAME: infrastructure/database/test.db
  # Scheduler
  SIDEKIQ_USER: <sidekiq username>
  SIDEKIQ_PASSWORD: <sidekiq password>

  # Redis Cloud
  REDISCLOUD_VISUALREPORTS_URL: redis://127.0.0.1:6379
  REDISCLOUD_SIDEKIQ_QUEUES_URL: redis://127.0.0.1:6379/

production: #on heroku
  REDIS_RACK_CACHE_METASTORE: /1/metastore
  REDIS_RACK_CACHE_ENTITYTORE: /1/entitystore
  REDISCLOUD_VISUALREPORTS_URL: <on heroku credential>
  REDISCLOUD_SIDEKIQ_QUEUES_URL: <on heroku credential>