---
development:
  APP_URL: http://localhost:9090
  # Security
  DB_KEY: 
  MSG_KEY: 
  # Sessions
  REDIS_URL: <on heroku credential>
  SESSION_SECRET: <some secrets>
  # AWS SQS
  AWS_ACCESS_KEY_ID: <on aws credential>
  AWS_SECRET_ACCESS_KEY: <on aws credential>
  AWS_REGION: <on aws sqs credential>
  RES_QUEUE_NAME: <on aws sqs credential>
  RES_QUEUE_URL: <on aws sqs credential>
  # Google
  GOOGLE_CLIENT_ID: <on gcp credential>
  GOOGLE_CLIENT_SECRET: <on gcp credential>
  REFRESH_TOKEN: <on gcp google drive api credential>
  SAMPLE_FILE_ID: <on google drive credential>
  VIZ_SAMPLE_FILE_ID: <on google drive credential>
  DB_FILENAME: infrastructure/database/dev.db

test:
  APP_URL: http://localhost:9090
  RACK_ENV: development
  # Security
  DB_KEY: 
  MSG_KEY: 
  # Sessions
  REDIS_URL: <on heroku credential>
  SESSION_SECRET: <some secrets>
  # AWS SQS
  AWS_ACCESS_KEY_ID: <on aws credential>
  AWS_SECRET_ACCESS_KEY: <on aws credential>
  AWS_REGION: <on aws sqs credential>
  RES_QUEUE_NAME: <on aws sqs credential>
  RES_QUEUE_URL: <on aws sqs credential>
  # Google
  GOOGLE_CLIENT_ID: <on gcp credential>
  GOOGLE_CLIENT_SECRET: <on gcp credential>
  REFRESH_TOKEN: <on gcp google drive api credential>
  SAMPLE_FILE_ID: <on google drive credential>
  VIZ_SAMPLE_FILE_ID: <on google drive credential>
  DB_FILENAME: infrastructure/database/test.db

production: #on heroku
  REDIS_RACK_CACHE_METASTORE: /1/metastore
  REDIS_RACK_CACHE_ENTITYTORE: /1/entitystore